### ISSUE TITLE
Add travis-check for running named-checkzone?

### ISSUE THREAD

**Issue by sventhomsen** [ffnord/nord-zone#7]
We should run named-checkzone on each pr.

One could use travis-ci, see https://github.com/sventhomsen/nord-zone/blob/add-travis-check/.travis.yml

Opinions?

**Comment by sventhomsen** [comment]
Sorry, that won't work...

**Comment by sventhomsen** [comment]
![bildschirmfoto 2016-01-18 um 21 34 52](https://cloud.githubusercontent.com/assets/1030935/12402154/5ee1e612-be2b-11e5-80ce-ea9ef47c905c.png)

**Comment by sventhomsen** [comment]
@Tarnatos , @rubo77 : any thoughts on that? This would provide some basic automativ syntax checks.

**Comment by Tarnatos** [comment]
Gern, wie macht man das?

**Comment by sventhomsen** [comment]
Ich baue mal einen ordentlichen PR.

**Comment by sventhomsen** [comment]
@rubo77 Kannst Du travis auf diesem Repo aktivieren? Die passende tavis.yml liegt bereit unter https://github.com/sventhomsen/nord-zone/tree/add-travis-for-syntax-check-of-zonefile

**Comment by rubo77** [comment]
gut so?
